from .formula import formula
from .mazedat import (afterparty, animals, appear, arial, asset, book_sub, build_rooms,
                      character_background, character_items, city_acts, city_events, city_themes,
                      civilized_job, clothing, district_themes, divine_domains, dun_acts, dun_enter,
                      dun_forms, dun_hazards, dun_layout, dun_rewards, dun_room_details, dun_rooms,
                      dun_ruins, dun_tricks, edible_plants, eth_efc, eth_ele, eth_form,
                      faction_goals, faction_traits, factions, hobbies, inn_adj, inn_nouns,
                      inn_quirks, insanities, job_type, land, liability, life_goal, lootType,
                      low_class_build, magic_formula, magic_ingredients, magic_words, mannerism,
                      materials, methods, misc_items, misfortune, mission_targets, missions,
                      mob_ability, mob_feat, mob_person, mob_tactics, mob_trait, mob_type, mob_weak,
                      mr_pages, mutations, name_big, name_female_big, name_female_full,
                      name_female_mr, name_full, name_male_big, name_male_full, name_male_mr, omens,
                      ordinarymat, personality, phy_efc, phy_ele, phy_form, phys, poisonous_plants,
                      potions, relationships, reputation, sea, secret, surname_all,
                      surname_lower_mr, surname_other, surname_upper_mr, tactical_building,
                      tactical_street, tool_items, trap_effects, trap_triggers, treasure_items,
                      treasure_traits, underworld_job, up_class_build, valuemats, weapon_items,
                      wild_acts, wild_discoveries, wild_hazards, wild_landmarks, wild_region_traits,
                      wild_regions, wild_structures, wilderness_job, worn_items)
from .potion_colors import Potion_colors, basic_colors, double_colors, potion_color, special_colors

tables = {
    "afterparty": afterparty,
    "all surnames": surname_all,
    "animals": animals,
    "appear": appear,
    "arial": arial,
    "asset": asset,
    "basic_colors": basic_colors,
    "book_sub": book_sub,
    "build_rooms": build_rooms,
    "character_background": character_background,
    "character_items": character_items,
    "city_acts": city_acts,
    "city_events": city_events,
    "city_themes": city_themes,
    "civilized_job": civilized_job,
    "clothing": clothing,
    "district_themes": district_themes,
    "divine_domains": divine_domains,
    "double_colors": double_colors,
    "dun_acts": dun_acts,
    "dun_enter": dun_enter,
    "dun_forms": dun_forms,
    "dun_hazards": dun_hazards,
    "dun_layout": dun_layout,
    "dun_rewards": dun_rewards,
    "dun_room_details": dun_room_details,
    "dun_rooms": dun_rooms,
    "dun_ruins": dun_ruins,
    "dun_tricks": dun_tricks,
    "edible_plants": edible_plants,
    "eth_efc": eth_efc,
    "eth_ele": eth_ele,
    "eth_form": eth_form,
    "faction_goals": faction_goals,
    "faction_traits": faction_traits,
    "factions": factions,
    "hobbies": hobbies,
    "inn_adj": inn_adj,
    "inn_nouns": inn_nouns,
    "inn_quirks": inn_quirks,
    "insanities": insanities,
    "jobs": job_type,
    "land": land,
    "liability": liability,
    "life_goal": life_goal,
    "lootType": lootType,
    "low_class_build": low_class_build,
    "magic_ingredients": magic_ingredients,
    "magic_words": magic_words,
    "mannerism": mannerism,
    "materials": materials,
    "methods": methods,
    "misc_items": misc_items,
    "misfortune": misfortune,
    "mission_targets": mission_targets,
    "missions": missions,
    "mob_ability": mob_ability,
    "mob_feat": mob_feat,
    "mob_person": mob_person,
    "mob_tactics": mob_tactics,
    "mob_trait": mob_trait,
    "mob_type": mob_type,
    "mob_weak": mob_weak,
    "mutations": mutations,
    "name_big": name_big,
    "name_female_big": name_female_big,
    "name_female_full": name_female_full,
    "name_female_mr": name_female_mr,
    "name_full": name_full,
    "name_male_big": name_male_big,
    "name_male_full": name_male_full,
    "name_male_mr": name_male_mr,
    "omens": omens,
    "ordinarymat": ordinarymat,
    "personality": personality,
    "phy_efc": phy_efc,
    "phy_ele": phy_ele,
    "phy_form": phy_form,
    "phys": phys,
    "poisonous_plants": poisonous_plants,
    "potion_color": potion_color,
    "potions": potions,
    "relationships": relationships,
    "reputation": reputation,
    "sea": sea,
    "secret": secret,
    "special_colors": special_colors,
    "surname_all": surname_all,
    "surname_lower_mr": surname_lower_mr,
    "surname_other": surname_other,
    "surname_upper_mr": surname_upper_mr,
    "tactical_building": tactical_building,
    "tactical_street": tactical_street,
    "tool_items": tool_items,
    "trap_effects": trap_effects,
    "trap_triggers": trap_triggers,
    "treasure_items": treasure_items,
    "treasure_traits": treasure_traits,
    "underworld_job": underworld_job,
    "up_class_build": up_class_build,
    "valuemats": valuemats,
    "weapon_items": weapon_items,
    "wild_acts": wild_acts,
    "wild_discoveries": wild_discoveries,
    "wild_hazards": wild_hazards,
    "wild_landmarks": wild_landmarks,
    "wild_region_traits": wild_region_traits,
    "wild_regions": wild_regions,
    "wild_structures": wild_structures,
    "wilderness_job": wilderness_job,
    "worn_items": worn_items,
}
printTables = [
    ("afterparty", "After the Party"),
    ("animals", "Animals"),
    ("appear", "Appearance"),
    ("arial", "Arial creature"),
    ("asset", "NPC Asset"),
    ("basic_colors", "Basic colors for potions"),
    ("book_sub", "Book Subject"),
    ("build_rooms", "building Rooms"),
    ("character_background", "Character Background"),
    ("character_items", "Starting Items"),
    ("city_acts", "City Activities"),
    ("city_events", "City Events"),
    ("city_themes", "City Themes"),
    ("civilized_job", "Civilized Job"),
    ("clothing", "Clothing Style"),
    ("district_themes", "District Themes"),
    ("divine_domains", "Divine Domains"),
    ("double_colors", "Exotic colors for potions"),
    ("dun_acts", "Dungeon Activities"),
    ("dun_enter", "Dun Entrance"),
    ("dun_forms", "Dungeon Forms"),
    ("dun_hazards", "Dungeon Hazards"),
    ("dun_layout", "Dungeon Layout"),
    ("dun_rewards", "Dungeon Rewards"),
    ("dun_room_details", "Dungeon Room Details"),
    ("dun_rooms", "Dungeon rooms"),
    ("dun_ruins", "Dungeon ruins"),
    ("dun_tricks", "Dungeon tricks"),
    ("edible_plants", "Edible Plants"),
    ("eth_efc", "Ethereal_Effect"),
    ("eth_ele", "Ethereal_Element"),
    ("eth_form", "Ethereal_Form"),
    ("faction_goals", "Faction Goals"),
    ("faction_traits", "Faction Traits"),
    ("factions", "Factions"),
    ("inn_adj", "Inn Adjectives"),
    ("inn_nouns", "Inn Nouns"),
    ("inn_quirks", "inn Quirks"),
    ("insanities", "Insanities"),
    ("jobs", "Jobs"),
    ("land", "Land Creatures"),
    ("liability", "Liability"),
    ("life_goal", "Life Goal"),
    ("lootType", "Loot"),
    ("low_class_build", "Lower Class Building"),
    ("magic_ingredients", "Magic Ingredients"),
    ("magic_words", "Magic Words"),
    ("mannerism", "Mannerism"),
    ("materials", "Materials"),
    ("methods", "Methods"),
    ("misc_items", "Miscellaneous Items"),
    ("misfortune", "Misfortunes"),
    ("mission_targets", "Mission Targets"),
    ("missions", "Missions"),
    ("mob_ability", "Monster Ability"),
    ("mob_feat", "Monster Feature"),
    ("mob_feats", "Monster Features"),
    ("mob_person", "Monster Personality"),
    ("mob_tactics", "Monster Tactics"),
    ("mob_trait", "Monster Traits"),
    ("mob_type", "Monster Type"),
    ("mob_weak", "Monster Weakness"),
    ("mutations", "Mutations"),
    ("name_big", "Big list of names"),
    ("name_female_big", "Big list of female names"),
    ("name_female_full", "Full list of female names (includes archaic & gothic)"),
    ("name_female_mr", "Female Names"),
    ("name_full", "Full list of names (includes archaic & gothic)"),
    ("name_male_big", "Big list of male names"),
    ("name_male_full", "Full list of males names (includes archaic & gothic)"),
    ("name_male_mr", "Male Names"),
    ("omens", "Omens"),
    ("ordinarymat", "Ordinary Materials"),
    ("personality", "Personality"),
    ("phy_efc", "Physical Effects"),
    ("phy_ele", "Physical Elements"),
    ("phy_form", "Physical Forms"),
    ("phys", "Physical Details"),
    ("poisonous_plants", "Poisonous Plants"),
    ("potion_color", "All potion colors"),
    ("potions", "Potions"),
    ("relationships", "Relationships"),
    ("reputation", "Reputations"),
    ("sea", "Sea Creatures"),
    ("secret", "NPC Secret"),
    ("special_colors", "Modified colors for potions"),
    ("surname_all", "Full list of Surnames"),
    ("surname_lower_mr", "Lower Class Surnames"),
    ("surname_other", "Additional Surnames"),
    ("surname_upper_mr", "Upper Class Surnames"),
    ("tactical_building", "Tactical Building Feature"),
    ("tactical_street", "Tactical Street Feature"),
    ("tool_items", "Tool Items"),
    ("trap_effects", "Trap Effects"),
    ("trap_triggers", "Trap Triggers"),
    ("treasure_items", "Treasure Items"),
    ("treasure_traits", "Treasure Traits"),
    ("underworld_job", "Underworld [npc] Job"),
    ("up_class_build", "Upper Class Building"),
    ("valuemats", "Valuable Materials"),
    ("weapon_items", "Weapon Items"),
    ("wild_acts", "Wilderness Activities"),
    ("wild_discoveries", "Wilderness Discoveries"),
    ("wild_hazards", "Wilderness Hazards"),
    ("wild_landmarks", "Wilderness Landmarks"),
    ("wild_region_traits", "Wilderness Region Traits"),
    ("wild_regions", "Wilderness Regions"),
    ("wild_structures", "Wilderness Structures"),
    ("wilderness_job", "Wilderness Jobs"),
    ("worn_items", "Worn Items"),
]

# create the maze rats pages formulas from mr_pages
Maze_Rats_pages = [(n, formula([tables[t] for t in p], [printTables(t) for t in p])) for n, p in mr_pages]

All_tables = [(n, tables[t]) for t, n in printTables]

npc_formula_part = [
    appear,
    phys,
    clothing,
    personality,
    mannerism,
    asset,
    liability,
    life_goal,
    misfortune,
    secret,
    reputation,
    relationships,
    lootType,
    omens,
    book_sub,
    job_type,
]
npc_labels_part = [
    "Appearance",
    "Physical detail",
    "Clothing",
    "Personality",
    "Mannerism",
    "Asset",
    "Liability",
    "Life Goal",
    "Misfortune",
    "Secret",
    "Reputation",
    "Relationships",
    "LootType",
    "Omens",
    "Book subject",
    "jobs",
]

mission_formula = formula(
    [missions, mission_targets, book_sub],
    [printTables[idx] for idx in ["missions", "target", "book_sub"]]
)

mob_form_feats = [
    mob_feat,
    mob_trait,
    mob_ability,
    mob_tactics,
    mob_person,
    mob_weak,
]
mob_form_feats_txt = [
    "mob_feat",
    "mob_trait",
    "mob_ability",
    "mob_tactics",
    "mob_person",
    "mob_weak",
]
mob_Formula = formula(
    [[magic_formula] + [mob_type] + mob_form_feats],
    magic_formula.labels + ["Monster type"] + [printTables[idx] for idx in mob_form_feats_txt]
)
mob_Double_Formula = formula(
    [[magic_formula] + [mob_type]*2 + mob_form_feats],
    magic_formula.labels + ["Monster type"]*2 + [printTables[idx] for idx in mob_form_feats_txt]
)
mob_Triple_Formula = formula(
    [[magic_formula] + [mob_type]*3 + mob_form_feats],
    magic_formula.labels + ["Monster type"]*3 + [printTables[idx] for idx in mob_form_feats_txt]
)

trinames = formula([name_male_big, name_female_big, surname_all], ["Male Name", "Female Name", "Surname"])
trinames_mr = formula([name_male_mr, name_female_mr, surname_all], ["Male Name", "Female Name", "Surname"])
trinames_full = formula([name_male_full, name_female_full, surname_all], ["Male Name", "Female Name", "Surname"])
names = formula([name_female_big + name_male_big, surname_all], ["Name", "Surname"])
names_mr = formula([name_female_mr + name_male_mr, surname_all], ["Name", "Surname"])
names_full = formula([name_female_full + name_male_full, surname_all], ["Name", "Surname"])

npc_formula = formula(
    names.formula, + npc_formula_part,
    names.labels + npc_labels_part,
)
npc_formula_mr = formula(
    names_mr.formula, + npc_formula_part,
    names_mr.labels + npc_labels_part,
)
npc_formula_full = formula(
    names_full.formula, + npc_formula_part,
    names_full.labels + npc_labels_part,
)

wild_formula = formula([
        wild_regions,
        wild_landmarks,
        wild_structures,
        wild_region_traits,
        wild_discoveries,
        wild_acts,
        wild_hazards,
    ],
    [
        "wild_regions",
        "wild_landmarks",
        "wild_structures",
        "wild_region_traits",
        "wild_discoveries",
        "wild_acts",
        "wild_hazards",
    ]
)
dun_macro_formula = formula(
    [
        dun_enter,
        dun_forms,
        dun_layout,
        dun_ruins,
        dun_acts,
        dun_rewards,
    ],
    [
        "dun_enter",
        "dun_forms",
        "dun_layout",
        "dun_ruins",
        "dun_acts",
        "dun_rewards",
    ]
)
dun_micro_formula = formula(
    [
        dun_acts,
        dun_rooms,
        dun_room_details,
        dun_tricks,
        dun_hazards,
        dun_rewards,
        trap_effects,
        trap_triggers,
    ],
    [
        "dun_acts",
        "dun_rooms",
        "dun_room_details",
        "dun_tricks",
        "dun_hazards",
        "dun_rewards",
        "trap_effects",
        "trap_triggers",
    ]
)
city_district_theme_formula = formula(
    [
        city_themes,
        district_themes,
    ],
    [
        "city_themes",
        "district_themes",
    ]
)
city_detail_formula = formula(
    [
        up_class_build,
        low_class_build,
        city_acts,
        build_rooms,
        tactical_street,
        tactical_building,
    ],
    [
        "up_class_build",
        "low_class_build",
        "city_acts",
        "build_rooms",
        "tactical_street",
        "tactical_building",
    ]
)
inn_formula = formula(
    [
        inn_adj,
        inn_nouns,
        inn_quirks,
    ],
    [
        "inn_adj",
        "inn_nouns",
        "inn_quirks",
    ]
)
faction_formula = formula(
    [
        factions,
        faction_traits,
        faction_goals,
    ],
    [
        "factions",
        "faction_traits",
        "faction_goals"
    ]
)

formulas = [
    ("Archaic Names M,F,S", trinames_full),
    ("Archaic Names M|F,S", names_full),
    ("City & District Themes", city_district_theme_formula),
    ("Double Monster", mob_Double_Formula),
    ("Dungeon Detail", dun_micro_formula),
    ("Dungeon Origin", dun_macro_formula),
    ("Factions", faction_formula),
    ("Magic", magic_formula),
    ("Maze Rats Names M,F,S", trinames_mr),
    ("Maze Rats Names M|F,S", names_mr),
    ("Mission", mission_formula),
    ("Monster", mob_Formula),
    ("Names M,F,S", trinames),
    ("Names M|F,S", names),
    ("NPC: Archaic names", npc_formula_full),
    ("NPC: Maze Rat names ", npc_formula_mr),
    ("NPC: More names)", npc_formula),
    ("Potion Colors", Potion_colors),
    ("Triple Monster", mob_Triple_Formula),
    ("Wilds", wild_formula),
]
