"""_summary_
    These are the tables from maze rats, each page is a formual, as well as other formuals

    This content is taken from Ben Milton's Maze Rats. https://legacy.drivethrurpg.com/product/197158/Maze-Rats
    Maze rats text is used here by the Creative Commons Attribution 4.0 International License. CC-BY
"""
# pylint: disable=too-many-lines
# This content is taken from Ben Milton's Maze Rats. https://legacy.drivethrurpg.com/product/197158/Maze-Rats
# Maze rats text is used here by the Creative Commons Attribution 4.0 International License. CC-BY

# addnames is not required for the maze rats content,
from .addnames import (name_female_apriori, name_female_gothic, name_female_old, name_female_short,
                       name_male_apriori, name_male_gothic, name_male_old, name_male_short,
                       surname_other)
from .formulas import MetaFormula


character_items = [
    "Animal Scent",
    "Bear Trap",
    "Bedroll",
    "Caltrops",
    "Chain, 10 ft.",
    "Chalk",
    "Chisel",
    "Crowbar",
    "Fishing Net",
    "Glass Marbles",
    "Glue",
    "Grappling Hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand drill",
    "Horn",
    "Iron spikes",
    "Iron tongs",
    "Lantern and Oil",
    "Large sack",
    "Lock-picks (3)",
    "Manacles",
    "Medicine (3)",
    "Metal File",
    "Rations (3)",
    "Rope 50 ft.",
    "Steel wire",
    "Shovel",
    "Steel mirror",
    "Ten foot Pole",
    "Tinderbox",
    "Torch",
    "Vial of Acid",
    "Vial of Poison",
    "Water-skin",
]
appear = [
    "Aquiline",
    "Athletic",
    "Barrel-Chested",
    "Boney",
    "Brawny",
    "Brutish",
    "Bullnecked",
    "Chisled",
    "Coltish",
    "Corpulent",
    "Craggy",
    "Delicate",
    "Furrowed",
    "Gaunt",
    "Gorgeous",
    "Grizzled",
    "Haggard",
    "Handsome",
    "Hideous",
    "Lanky",
    "Pudgy",
    "Ripped",
    "Rosy",
    "Scrawny",
    "Sinewy",
    "Slender",
    "Slumped",
    "Solid",
    "Square-Jawed",
    "Statuesque",
    "Towering",
    "Trim",
    "Weathered",
    "Willowy",
    "Wiry",
    "Wrinkled",
]
phys = [
    "Acid Scars",
    "Battle Scars",
    "Birthmark",
    "Braided hair",
    "Brand Mark",
    "Broken Nose",
    "Bronze skinned",
    "Burn scars",
    "Bushy eyebrows",
    "Curly hair",
    "Dark Skinned",
    "Dread-locks",
    "Exotic accent",
    "Flogging scars",
    "Freckles",
    "Gold tooth",
    "Hoarse voice",
    "Huge Beard",
    "Long Hair",
    "Matted Hair",
    "Missing ear",
    "Missing teeth",
    "Mustache",
    "Muttonchops",
    "Nine fingers",
    "Oiled hair",
    "One-eyed",
    "Pale skinned",
    "Piercings",
    "Ritual Scars",
    "Sallow Skin",
    "Shaved head",
    "Sunburned",
    "Tangled hair",
    "Tattoos",
    "Topknot",
]
character_background = [
    "alchemist",
    "Beggar-prince",
    "Blackmailer",
    "Bounty-hunter",
    "Chimney-sweep",
    "Coin-clipper",
    "Contortionist",
    "Counterfeiter",
    "Cultist",
    "Cutpurse",
    "Debt-collector",
    "Deserter",
    "Fence",
    "Fortuneteller",
    "Gallery Slave",
    "Gambler",
    "Gravedigger",
    "Headsman",
    "Hedge Knight",
    "Highwayman",
    "Housebreaker",
    "Kidnapper",
    "Mad prophet",
    "Mountebank",
    "Peddler",
    "Pit-fighter",
    "Poisoner",
    "Rat-catcher",
    "Scrivener",
    "Sell-sword",
    "Slave",
    "Smuggler",
    "Street performer",
    "Tattooist",
    "Urchin",
    "Usurer",
]
clothing = [
    "Antique",
    "Battle-torn",
    "Bedraggled",
    "Blood-stained",
    "Ceremonial",
    "Dated",
    "Decaying",
    "Eccentric",
    "Elegant",
    "Embroidered",
    "Exotic",
    "Fashionable",
    "Flamboyant",
    "Food-Stained",
    "Formal",
    "Frayed",
    "Frumpy",
    "Garish",
    "Grimy",
    "Haute Couture",
    "Lacy",
    "Livery",
    "Mud-stained",
    "Ostentatious",
    "Oversized",
    "Patched",
    "Patterned",
    "Perfumed",
    "Practical",
    "Rumpled",
    "Sigils",
    "Singed",
    "Tasteless",
    "Undersized",
    "Wine-stained",
    "Wornout",
]
personality = [
    "Bitter",
    "Brave",
    "Cautious",
    "Chipper",
    "Contrary",
    "Cowardly",
    "Cunning",
    "Driven",
    "Entitled",
    "Gregarious",
    "Grumpy",
    "Heartless",
    "Honor-bound",
    "Hotheaded",
    "Inquisitive",
    "Irascible",
    "Jolly",
    "A Know-it-all",
    "Lazy",
    "Loyal",
    "Menacing",
    "Mopey",
    "Nervous",
    "Protective",
    "Righteous",
    "Rude",
    "Sarcastic",
    "Savage",
    "Scheming",
    "Serene",
    "Spacey",
    "Stoic",
    "Stubborn",
    "Stuck-up",
    "Suspicious",
    "Wisecracking",
]
mannerism = [
    "Anecdotes",
    "Breathy",
    "Chuckles",
    "Clipped",
    "Cryptic",
    "Deep voiced",
    "Drawl",
    "Enunciates",
    "Flowery Speech",
    "Gravelly voiced",
    "Highly Formal",
    "Hypnotic",
    "Interrupts",
    "Laconic",
    "Laughs",
    "Long Pauses",
    "Melodious",
    "Monotone",
    "Mumbles",
    "Narrates",
    "Overly casual",
    "Quaint Sayings",
    "Rambles",
    "Random Facts",
    "Rapid-fire",
    "Rhyming",
    "Robotic",
    "Slow speech",
    "Speechifies",
    "Squeaky",
    "Street slang",
    "Stutters",
    "Talks to self",
    "Trails off",
    "Very loud",
    "Whispers",
]
hobbies = [
    "Archaeology",
    "Art collecting",
    "Bad fiction",
    "Calligraphy",
    "Card games",
    "Clockwork",
    "Collecting Cats",
    "Cuisine",
    "Dark Lore",
    "Dog Breeding",
    "Embroidery",
    "Exercise",
    "Falconry",
    "Fashion",
    "Fishing",
    "Foreign cultures",
    "Gardening",
    "History",
    "Horse Racing",
    "Hunting",
    "Instrument",
    "Knitting",
    "Lawn gnomes",
    "Mountaineering",
    "Opera",
    "Painting",
    "Poetry",
    "Puzzle-solving",
    "Riddling",
    "Science",
    "Falconry",
    "Fishing",
    "Foreign cultures",
    "Gardening",
    "History",
    "Sculpture",
    "Sketching",
    "Smoking",
    "Theater",
    "Weaving",
    "whiskey",
]
phy_efc = [
    "Animating",
    "Attracting",
    "Binding",
    "Blossoming",
    "Consuming",
    "Creeping",
    "Crushing",
    "Diminishing",
    "Dividing",
    "Duplicating",
    "Enveloping",
    "Expanding",
    "Fusing",
    "Grasping",
    "Hastening",
    "Hindering",
    "Illuminating",
    "Imprisoning",
    "Levitating",
    "Opening",
    "Petrifying",
    "Phasing",
    "Piercing",
    "Pursuing",
    "Reflecting",
    "Regenerating",
    "Rending",
    "Repelling",
    "Sealing",
    "Shielding",
    "Spawning",
    "Transporting"
]
phy_ele = [
    "Acid",
    "Amber",
    "Bark",
    "Blood",
    "Bone",
    "Brine",
    "Clay",
    "Crystal",
    "Ember",
    "Fungus",
    "Glass",
    "Honey",
    "Ice",
    "Wood",
    "Lava",
    "Moss",
    "Obsidian",
    "Oil",
    "Poison",
    "Rat",
    "Salt",
    "Sand",
    "Sap",
    "Serpent",
    "Slime",
    "Stone",
    "Tar",
    "Thorn",
    "Vine",
    "Water",
    "Wine",
    "Wood"
]
phy_form = [
    "Altar",
    "Armor",
    "Arrow",
    "Beast",
    "Blade",
    "Chain",
    "Chariot",
    "Claw",
    "Cloak",
    "Colossus",
    "Crown",
    "Elemental",
    "Eye",
    "Fountain",
    "Hammer",
    "Horn",
    "Key",
    "Mask",
    "Monolith",
    "Pit",
    "Prison",
    "Sentinel",
    "Servant",
    "Shield",
    "Spear",
    "Swarm",
    "Tentacle",
    "Throne",
    "Torch",
    "Trap",
    "Wall",
    "Web"
]
eth_efc = [
    "Altar",
    "Armor",
    "Arrow",
    "Beast",
    "Blade",
    "Chain",
    "Chariot",
    "Claw",
    "Cloak",
    "Colossus",
    "Crown",
    "Elemental",
    "Eye",
    "Fountain",
    "Hammer",
    "Horn",
    "Key",
    "Mask",
    "Monolith",
    "Pit",
    "Prison",
    "Sentinel",
    "Servant",
    "Shield",
    "Spear",
    "Swarm",
    "Tentacle",
    "Throne",
    "Torch",
    "Trap",
    "Wall",
    "Web"
]
eth_ele = [
    "Ash",
    "Chaos",
    "Distortion",
    "Dream",
    "Dust",
    "Echo",
    "Fire",
    "Fog",
    "Ghost",
    "Harmony",
    "Heat",
    "Light",
    "Lightning",
    "Memory",
    "Mind",
    "Mutation",
    "Plague",
    "Plasma",
    "Rain",
    "Rot",
    "Shadow",
    "Smoke",
    "Snow",
    "Star",
    "Stasis",
    "Steam",
    "Thunder",
    "Time",
    "Void",
    "Warp",
    "Whisper",
    "Wind"
]
eth_form = [
    "Aura",
    "Beacon",
    "Beam",
    "Blast",
    "Blob",
    "Bolt",
    "Bubble",
    "Call",
    "Cascade",
    "Circle",
    "Cloud",
    "Coil",
    "Cone",
    "Cube",
    "Dance",
    "Disk",
    "Field",
    "Gaze",
    "Loop",
    "Portal",
    "Pulse",
    "Pyramid",
    "Ray",
    "Sphere",
    "Spray",
    "Storm",
    "Swarm",
    "Torrent",
    "Touch",
    "Vortex",
    "Wave",
    "Word"
]
magic_words = phy_efc + phy_ele + phy_form + eth_efc + eth_ele + eth_form
magic_formula = MetaFormula([
        [phy_efc, phy_form],
        [phy_efc, eth_form],
        [eth_efc, phy_form],
        [eth_efc, eth_form],
        [phy_ele, phy_form],
        [phy_ele, eth_form],
        [eth_ele, phy_form],
        [eth_ele, eth_form],
        [phy_efc, phy_ele],
        [phy_efc, eth_ele],
        [eth_efc, phy_ele],
        [eth_efc, eth_ele]
    ],
    ["Word A", "Word B"],
    "Magic Spell"
)

effects = phy_efc + eth_efc
elements = phy_ele + eth_ele
arial = [
    "Albatross",
    "Bat",
    "Beetle",
    "Butterfly",
    "Condor",
    "Crane",
    "Crow",
    "Dragonfly",
    "Eagle",
    "Falcon",
    "Firefly",
    "Flamingo",
    "FlyingSquirrel",
    "Goose",
    "Gull",
    "Hummingbird",
    "Locust",
    "Magpie",
    "Mantis",
    "Mockingbird",
    "Mosquito",
    "Moth",
    "Owl",
    "Parrot",
    "Peacock",
    "Pelican",
    "Rooster",
    "Sparrow",
    "Swan",
    "Vulture",
    "Wasp",
    "Woodpecker"
]
land = [
    "Ant",
    "Ape",
    "Badger",
    "Bear",
    "Boar",
    "Caterpillar",
    "Centipede",
    "Chameleon",
    "Elephant",
    "Ferret",
    "Fox",
    "Giraffe",
    "Goat",
    "Horse",
    "Human",
    "Mole",
    "Ostrich",
    "Ox",
    "Porcupine",
    "Rabbit",
    "Raccoon",
    "Rat",
    "Rhinoceros",
    "Scorpion",
    "Sheep",
    "Slug",
    "Snail",
    "Snake",
    "Spider",
    "Squirrel",
    "Tiger",
    "Wolf"
]
sea = [
    "Alligator",
    "Amoeba",
    "Angler-fish",
    "Beaver",
    "Clam",
    "Crab",
    "Dolphin",
    "Eel",
    "Frog",
    "Hippopotamus",
    "Jellyfish",
    "Leech",
    "Lobster",
    "Manatee",
    "MantaRay",
    "Muskrat",
    "Narwhal",
    "Newt",
    "Octopus",
    "Otter",
    "Penguin",
    "Platypus",
    "Salamander",
    "SeaUrchin",
    "Seal",
    "Shark",
    "Shrimp",
    "Squid",
    "Swordfish",
    "Turtle",
    "Walrus",
    "Whale"
]
mob_type = [arial, land, sea]
animals = arial + land + sea
animal_form = (animals, " Form")
mob_feat = [
    "Antlers",
    "Beak",
    "Carapace",
    "Claws",
    "Compound eyes",
    "Eye stalks",
    "Fangs",
    "Fins",
    "Fur",
    "Gills",
    "Hooves",
    "Horns",
    "Long tongue",
    "Many-eyed",
    "Many-limbed",
    "Pincers",
    "Plates",
    "Plumage",
    "Proboscis",
    "Scales",
    "Segments",
    "Shaggy hair",
    "shell",
    "Spikes",
    "Spinnerets",
    "Stinger",
    "Suction Cups",
    "Tail",
    "Talons",
    "Tentacles",
    "Tusks",
    "Wings"
]
mob_trait = [
    phy_ele,
    eth_ele,
    "Amphibious",
    "Bloated",
    "Brittle",
    "Clay-like",
    "Colossal",
    "Crystalline",
    "Decaying",
    "Ethereal",
    "Eyeless",
    "Fluffy",
    "Fungal",
    "Gelatinous",
    "Geometric",
    "Hardened",
    "Illusory",
    "Intelligent",
    "Iridescent",
    "Luminous",
    "Many-headed",
    "Mechanical",
    "Planar",
    "Reflective",
    "Rubbery",
    "Shadowy",
    "Sharp",
    "Skeletal",
    "Slimy",
    "Sticky",
    "Tiny",
    "Translucent"
]
mob_ability = [
    phy_efc,
    eth_efc,
    "Absorbing",
    "Acid blood",
    "Anti-magic",
    "Blinding",
    "Breath weapons",
    "Camouflaging",
    "Duplicating",
    "Electric",
    "Entangling",
    "Exploding",
    "Flying",
    "Gaze weapon",
    "Hypnotizing",
    "Invisible",
    "Life-draining",
    "Mimicking",
    "Paralyzing",
    "Phasing",
    "Poisonous",
    "Reflective",
    "Regenerating",
    "Shape-shifting",
    "Spell-casting",
    "Stealthy",
    "Strangling",
    "Super-Strength",
    "Telekinetic",
    "Teleporting",
    "Vampiric",
    "Wall-crawling"
]
mob_tactics = [
    "Ambush",
    "Call for support",
    "Capture",
    "Charge",
    "Climb foes",
    "Create barrier",
    "Deceive",
    "Disorient",
    "Encircle",
    "Evade",
    "Gang-up",
    "Gather strength",
    "Go berserk",
    "Harry",
    "Hurl foes",
    "Immobilize",
    "Manipulate",
    "Mock",
    "Order minion",
    "Protect leader",
    "Protect self",
    "Scatter foes",
    "Stalk",
    "Steal from",
    "Swarm",
    "Target leader",
    "Target nearest",
    "Target strongest",
    "Target richest",
    "Target weakest",
    "Toy with",
    "Use terrain"
]
mob_person = [
    "Alien",
    "Aloof",
    "Bored",
    "Cautious",
    "Cowardly",
    "Curious",
    "Devious",
    "Distract-able",
    "Educated",
    "Embittered",
    "Envious",
    "Erudite",
    "Fanatical",
    "Forgetful",
    "Generous",
    "Hateful",
    "Honorable",
    "Humble",
    "Jaded",
    "Jovial",
    "Legalistic",
    "Megalomaniac",
    "Meticulous",
    "Mystical",
    "Obsessive",
    "Paranoid",
    "Polite",
    "Psychopathic",
    "Sophisticated",
    "Touchy",
    "Unimpressed",
    "Vain"
]
valuable_materials = [
    "Alabaster",
    "Amber",
    "Aquamarine",
    "Azurite",
    "Beryl",
    "Black Pearl",
    "Bloodstone",
    "Bone china",
    "Chalcedony",
    "Cinnabar",
    "Coral",
    "Diamond",
    "Ebony",
    "Emerald",
    "Fire Agate",
    "Garnet",
    "Gold",
    "Ivory",
    "Jade",
    "Jasper",
    "Jet",
    "Lapis Lazuli",
    "Malachite",
    "Moonstone",
    "Onyx",
    "Opal",
    "Pearl",
    "Platinum",
    "Porcelain",
    "Ruby",
    "Sapphire",
    "Serpentine",
    "Silver",
    "Star Iron",
    "Topaz",
    "Turquoise"
]
weapon_items = [
    "Battleaxe",
    "Blowpipe",
    "Claymore",
    "Club",
    "Crossbow",
    "Cutlass",
    "Dagger",
    "Flail",
    "Flanged Mace",
    "Glaive",
    "Halberd",
    "Hammer",
    "Hatchet",
    "Hunting Knife",
    "Longbow",
    "Mace",
    "Maul",
    "Morningstar",
    "Pike",
    "Scimitar",
    "Shiv",
    "Short-bow",
    "Sickle",
    "Sling",
    "Spear",
    "Staff",
    "Stake",
    "Stiletto",
    "Throwing axe",
    "War-hammer"
]
insanities = [
    animal_form,
    ('"', mob_ability, '"'),
    ('"', mob_feat, '"'),
    ('"', mob_trait, '"'),
    ("new personality:", personality),
    "Always lies",
    "Always polite",
    "Cannot count",
    "Cannot lie",
    "Face blind",
    "Fears birds",
    "Fears blood",
    "Fears books",
    "Fears darkness",
    "Fears fire",
    "Fears gold",
    "Fears horses",
    "Fears iron",
    "Fears music",
    "Fears own hand",
    "Fears PC",
    "Fears Rain",
    "Fears Rivers",
    "Fears Silence",
    "Fears Sleep",
    "Fears Sunlight",
    "Fears the Moon",
    "Fears Trees",
    '"Genius"',
    '"Gorgeous"',
    "Hates Violence",
    '"Invisible"',
    '"Invulnerable"',
    "Must sing",
    "Says thoughts",
    "Sees dead people",
]
methods = [
    "Alchemy",
    "Charm",
    "Eloquence",
    "Blackmail",
    "Commerce",
    "Espionage",
    "Bluster",
    "Cronies",
    "Fast-talking",
    "Bribery",
    "Debate",
    "Favors",
    "Bullying",
    "Deceit",
    "Hard Work",
    "Bureaucracy",
    "Deduction",
    "Humor",
    "Investigation",
    "Negotiation",
    "Rumors",
    "Legal maneuvers",
    "Persistence",
    "Sabotage",
    "Manipulation",
    "Piety",
    "Teamwork",
    "Misdirection",
    "Preparation",
    "Theft",
    "Money",
    "Quick Wit",
    "Threats",
    "Nagging",
    "Research",
    "Violence",
]
mob_weak = [
    valuable_materials,
    weapon_items,
    phy_ele,
    eth_ele,
    insanities,
    methods,
    "Bells",
    "Birdsong",
    "Children",
    "Cold",
    "Cold Iron",
    "Competition",
    "Conversation",
    "Deformity",
    "Flattery",
    "Flowers",
    "Gifts",
    "Gold",
    "Heat",
    "Holy Icon",
    "Holy Water",
    "Home cooking",
    "Mirrors",
    "Mistletoe",
    "Moonlight",
    "Music",
    "Phylactery",
    "Rituals",
    "Silver",
    "Sunlight",
    "Tears",
    "True Name",
    "Weak spot",
    "Wine",
    "Wormwood"
]
mutations = [
    "Ages",
    "Attracts Birds",
    "Child-form",
    "Corpulence",
    "Covered in hair",
    (animals, " Arms"),
    (animals, " Eyes"),
    (animals, " Head"),
    (animals, " Legs"),
    (animals, " Mouth"),
    (animals, " Skin"),
    animal_form,
    "Cyclops",
    "Extra Arms",
    "Extra Eyes",
    "Extra Legs",
    "Forked Tongue",
    "Gender Swap",
    "Hunchback",
    "Sex change",
    "Long Arms",
    "Lose all hair",
    "Loses Teeth",
    "No Eyes",
    "No Mouth",
    (phy_ele, " Skin"),
    "Second Face",
    "Sheds Skin",
    "Shrinks",
    "Shrivels",
    "Skin boils",
    "Slime Trail",
    "Translucent Skin",
    "Weeps blood",
    mob_feat,
    mob_trait,
]
name_female_mr = [
    "Adelaide",
    "Alma",
    "Barsaba",
    "Beatrix",
    "Bianca",
    "Cleopha",
    "Clover",
    "Constance",
    "Damaris",
    "Daphne",
    "Demona",
    "Elsbeth",
    "Esme",
    "Fern",
    "Hester",
    "Hippolyta",
    "Jessamine",
    "Jilly",
    "Minerva",
    "Morgot",
    "Nerissa",
    "Odette",
    "Olga",
    "Olive",
    "Orchid",
    "Pepper",
    "Phoebe",
    "Piety",
    "Poppy",
    "Silences",
    "Sybil",
    "Trillby",
    "Tuesday",
    "Ursula",
    "Vivian",
    "Wendy",
    "Zora",
]
name_male_mr = [
    "Balthazar",
    "Basil",
    "Bertram",
    "Blaxton",
    "Chadwick",
    "Clovis",
    "Destrian",
    "Ellis",
    "Erasmus",
    "Faustus",
    "Finn",
    "Fitzhugh",
    "Florian",
    "Fox",
    "Godwin",
    "Hannible",
    "Jasper",
    "Jiles",
    "Jules",
    "Leopold",
    "Merrick",
    "Mortimer",
    "Ogden",
    "Orion",
    "Oswald",
    "Percival",
    "Peregrine",
    "Quentin",
    "Redmaine",
    "Reinhold",
    "silas",
    "Stilton",
    "Stratford",
    "Tenpiece",
    "Waverly",
    "Webster"
]
surname_lower_mr = [
    "Barrow",
    "Berrycloth",
    "Bettleman",
    "Bird-Whistle",
    "Bobitch",
    "Chips",
    "Coffin",
    "Cromupling",
    "Culpepper",
    "Dankworth",
    "Dreggs",
    "Gimble",
    "Graveworm",
    "Greelish",
    "Hardwick",
    "Hatman",
    "Hovel",
    "Knibbs",
    "Midnighter",
    "Needle",
    "Nethercoat",
    "Pestle",
    "Relish",
    "Rumbold",
    "Rummaage",
    "Sallow",
    "Saltmarsh",
    "Silverless",
    "Skitter",
    "Slee",
    "Slitherly",
    "Stoker",
    "Tartwater",
    "Tumbler",
    "Villin"
]
surname_upper_mr = [
    "Belvedere",
    "Bithesea",
    "Calaver",
    "Carvolo",
    "De Rippe",
    "Droll",
    "Dunlow",
    "Edevane",
    "Erelong",
    "Febland",
    "Fernsby",
    "Fisk",
    "Gastrell",
    "Girdwood",
    "Gorgon",
    "Grimeson",
    "Gurger",
    "Hitheryon",
    "La Marque",
    "Malmora",
    "Miter",
    "Oblington",
    "Onymous",
    "Phillifent",
    "Portendofter",
    "Romatet",
    "Rothery",
    "Skorbeck",
    "Slora",
    "Southwark",
    "Stavish",
    "vandermeer",
    "Webley",
    "wellbelove",
    "Westergren",
    "Wilberforce"
]
factions = [
    "Art movement",
    "Beggar’s guild",
    "Black market",
    "Brotherhood",
    "City guard",
    "Conspiracy",
    "Craft Guild",
    "Crime Family",
    "Dark cult",
    "Explorer’s club",
    "Free company",
    "Gourmand club",
    "Heist crew",
    "Heretical sect",
    "High council",
    "Hired killers",
    "Local militia",
    "National church",
    "Noble house",
    "Outlander clan",
    "Outlaw gang",
    "Political party",
    "Religious order",
    "Religious sect",
    "Resistance",
    "Royal army",
    "Royal house",
    "Scholar’s circle",
    "Secret society",
    "Spy network",
    "Street artists",
    "Street gang",
    "Street musicians",
    "Theater troupe",
    "Trade company",
]
asset = [
    "Authority",
    "Avoids Detection",
    "Calls in favors",
    "Charming",
    "Cooks the books",
    "Erases evidence",
    "Excellent Liar",
    "Extremely rich",
    (factions, " Leader"),
    (factions, " Member"),
    "Feared",
    "Fortified base",
    "Gorgeous",
    "Heart rumors",
    "Huge family",
    "Huge library",
    "Impersonator",
    "Interrogator",
    "Knows a guy",
    "Knows a way in",
    "Launders money",
    "Learned",
    "Local Celebrity",
    "Local knowledge",
    "Loyal henchmen",
    "Middling oracle",
    "Nothing to lose",
    "Owns the guards",
    "Powerful spouse",
    "Procures gear",
    "Pulls the strings",
    "Secret lab",
    "Sells contraband",
    "Smuggles goods",
    "Spy network",
    "War hero"
]
liability = [
    "Addiction",
    "Alcoholic",
    "Corrupt ally",
    "Coward",
    "Decadent",
    "Forbidden love",
    "Gambler",
    "Glutton",
    "Greedy",
    "Heretic",
    "Huge Debts",
    "Imposter",
    ("insane: ", insanities),
    "Jealous",
    "Leaves evidence",
    "Many enemies",
    "Misinformed",
    "Money trail",
    "Narcissist",
    "Needs medicine",
    "OCD",
    "Paranoid",
    "Partyer",
    "Poor equipment",
    "Protective",
    "Scandalous",
    "Softhearted",
    "Strict routines",
    "Superstitious",
    "Suspicious",
    "Temper",
    "Trusting",
    "Vulnerable base",
    "Wanted",
    "Weak-willed",
    "Widely despised"
]
misc_items = [
    "Bowl",
    "Brass bell",
    "Brooch",
    "Carved figuring",
    "Cup",
    "Deck of cards",
    "Drawing",
    "Foreign Coin",
    "Game piece",
    "Glass eye",
    "Glass jar",
    "Hair Comb",
    "Handkerchief",
    "Hinged Box",
    "Hourglass",
    "Human tooth",
    "Hunting horn",
    "Loaded Dice",
    "Long fork",
    "Numbered Key",
    "Oil Lamp",
    "Paint pot",
    "Pencil",
    "Purse",
    "Quill pen & ink",
    "Salve",
    "Scissors",
    "Scroll",
    "Sealed Letter",
    "Sewing needle",
    "Shaving razor",
    "Silver Button",
    "Skull",
    "Tobacco pipe",
    "Wine bottle"
]
worn_items = [
    "Belt",
    "Blouse",
    "Boots",
    "Bracelet",
    "Breastplate",
    "Brigandine",
    "Cincture",
    "Cloak",
    "Coat",
    "Dress",
    "Earing",
    "Eye-patch",
    "Gauntlets",
    "Glove",
    "Gown",
    "Hat",
    "Helmet",
    "Hose",
    "Leather Armor",
    "Locker",
    "Mail Shirt",
    "Mask",
    "Necklace",
    "Padded Armor",
    "Plate Mail",
    "Ring",
    "Robe",
    "Sandals",
    "Scarf",
    "Shirt",
    "Shoes",
    "Skirt",
    "Slippers",
    "Socks",
    "Trousers",
    "Veil"
]
tool_items = [
    "Acid flask",
    "bear trap",
    "Bellows",
    "Bolt-cutters",
    "Chain",
    "Chisel",
    "Crowbar",
    "Door ram",
    "Ear trumpet",
    "Fire oil",
    "Fishing hook",
    "Goggles",
    "Grappling hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand drill",
    "Lantern",
    "Lens",
    "Lock/key",
    "Lock-picks",
    "Manacles",
    "Metal File",
    "Mortar and pestle",
    "Needle",
    "Pickaxe",
    "Pitchfork",
    "Pliers",
    "Pole",
    "Pulleys",
    "Rope",
    "Scissors",
    "Shovel",
    "Spikes",
    "Steel wire",
    "Tongs"
]
treasure_items = [
    "Alchemy Recipe",
    "Amulet",
    "Astrolabe",
    "Blueprints",
    "Calligraphy",
    "Carpet",
    "Compass",
    "Contract",
    "Crown",
    "Crystal",
    "Deed",
    "Embroidery",
    "Fine China",
    "Fine Liquor",
    "Instrument",
    "Magical book",
    "Microscope",
    "Music box",
    "Orrery",
    "Painting",
    "Perfume",
    "Prayer book",
    "Printing block",
    "Rare textile",
    "Royal Robes",
    "Saint's Relic",
    "Scrimshaw",
    "Sextant",
    "Sheet music",
    "Signet ring",
    "Silverware",
    "Spices",
    "Spyglass",
    "Tapestry",
    "Telescope",
    "Treasure map"
]
lootType = [
    misc_items,
    worn_items,
    weapon_items,
    tool_items,
    treasure_items,
]
life_goal = [
    "A better life",
    "Acceptance",
    ("Acquire ", lootType),
    ("Craft ", lootType),
    ("Destroy ", factions),
    ("Destroy ", lootType),
    "Enlightenment",
    "Fame",
    ("Find ", factions),
    "Freedom",
    "Glory",
    "Impress NPC",
    "Infamy",
    ("Infiltrate ", factions),
    "Justice",
    "Kidnap NPC",
    ("Lead ", factions),
    "Learning",
    "Locate NPC",
    "Love",
    "Mastery",
    "Power",
    "Reach Location",
    "Rescue NPC",
    "Resolve dispute",
    ("Restore ", factions),
    "Reveal a secret",
    "Revenge",
    ("Sabotage ", factions),
    "serve a deity",
    "Serve evil",
    ("Serve ", factions),
    "Serve ideology",
    "Serve leader",
    "Serve the needy",
    "Gain Wealth"
]
misfortune = [
    "Abandoned",
    "Addicted",
    "Arrested",
    "Blackmailed",
    "Burgled",
    "Challenged",
    "Condemned",
    "Crippled",
    "Cursed",
    "Defrauded",
    "Demoted",
    "Depressed",
    "Discredited",
    "Dismissed",
    "Disowned",
    "Exiled",
    "Famished",
    "Forgotten",
    "Framed",
    "Haunted",
    "Humiliated",
    "Impoverished",
    "Kidnapped",
    "Lost",
    "Mobbed",
    "Mutilated",
    "Overworked",
    "Poisoned",
    "Pursued",
    "Rejected",
    "Replaced",
    "Robbed",
    "Sick",
    "Sued",
    "Suspected",
    "Transformed"
]
secret = [
    "Addicted",
    "Artificial",
    "Assassin",
    "Bankrupt",
    "Beholden",
    "Counterspy",
    "Cultist",
    "Demigod",
    "Evil lineage",
    "an Exile",
    "Fence",
    "Fugitive",
    "Ghost",
    "Has a child",
    "Heretic",
    "High born",
    "Huge Fortune",
    "Illusion",
    "Insurrectionist",
    "Low born",
    "Married",
    "Mind-controlled",
    misfortune,
    "Monster hunter",
    "Non-human",
    "Polygamist",
    "NPC",
    "Protects relic",
    "Scandalous birth",
    "Secret police",
    "Serial killer",
    "Smuggler",
    "Spy",
    "Time traveler",
    "Transformed",
    "War criminal"
]
reputation = [
    "Ambitious",
    "Authoritative",
    "Boor",
    "Borrower",
    "Celebrity",
    "Charitable",
    "Misanthrope",
    "Miser",
    "Neighborly",
    "Nut-job",
    "Obnoxious",
    "Overeducated",
    "Cheat",
    "Dangerous",
    "Entertainer",
    "Gossip",
    "Hardworking",
    "Holy",
    "Partyer",
    "Pious",
    "Proper",
    "Prophet of doom",
    "Repulsive",
    "Respected",
    "Riffraff",
    "Scandalous",
    "Slime ball",
    "Terrifying",
    "Weirdo",
    "Wise"
]
relationships = [
    "Adviser",
    "Blackmailer",
    "Business partner",
    "Business rival",
    "Buyer",
    "Captor",
    "Client",
    "Confidant",
    "Debtor",
    "Disciple",
    "Guardian",
    "Henchman",
    "Idol",
    "Informant",
    "Master",
    "Mentor",
    "Nemesis",
    "Offspring",
    "Parent",
    "Patron",
    "Political rival",
    "Prisoner",
    "Protégé",
    "Quarry",
    "Right hand",
    "Romantic rival",
    "Servant",
    "Sibling",
    "Social rival",
    "Spouse",
    "Stalker",
    "Suitor",
    "Supplicant",
    "Supplier",
    "Sweetheart",
    "Unrequited love",
]
underworld_job = [
    "Alchemist",
    "Beggar-prince",
    "Blackmailer",
    "Bounty-hunter",
    "Chimney sweep",
    "Coin-clipper",
    "Contortionist",
    "Counterfeiter",
    "Cultist",
    "Cutpurse",
    "Debt-collector",
    "Deserter",
    "Fence",
    "Fortuneteller",
    "Galley slave",
    "Gambler",
    "Gravedigger",
    "Headsman",
    "Hedge Knight",
    "Highwayman",
    "Housebreaker",
    "Kidnapper",
    "Mad prophet",
    "Mountebank",
    "Peddler",
    "Pit-fighter",
    "Poisoner",
    "Rat-catcher",
    "Scrivener",
    "Sell-sword",
    "Slave",
    "Smuggler",
    "Street performer",
    "Tattooist",
    "Urchin",
    "Usurer",
]
civilized_job = [
    "Acolyte",
    "Actor",
    "Apothecary",
    "Baker",
    "Barber",
    "Blacksmith",
    "Brewer",
    "Bureaucrat",
    "Butcher",
    "Carpenter",
    "Clockmaker",
    "Courier",
    "Courtier",
    "Diplomat",
    "Fishmonger",
    "Guard",
    "Haberdasher",
    "Innkeeper",
    "Item-Seller",
    "Jeweler",
    "Knight",
    "Locksmith",
    "Mason",
    "Miller",
    "Musician",
    "Noble",
    "Painter",
    "Priest",
    "Scholar",
    "Scribe",
    "Sculptor",
    "Shipwright",
    "Soldier",
    "Taylor",
    "Taxidermist",
    "Wigmaker",
]
wilderness_job = [
    "Apiarist",
    "Bandit",
    "Caravan Guard",
    "Caravaneer",
    "Druid",
    "Exile",
    "Explorer",
    "Farmer",
    "Fisherman",
    "Forager",
    "Fugitive",
    "Hedge Wizard",
    "Hermit",
    "Hunter",
    "Messenger",
    "Minstrel",
    "Monk",
    "Monster Hunter",
    "Outlander",
    "Tinker",
    "Pilgrim",
    "Poacher",
    "Raider",
    "Ranger",
    "Rancher",
    "Sage",
    "Scavenger",
    "Scout",
    "Shepherd",
    "Seer",
    "Surveyor",
    "Tomb raider",
    "Trader",
    "Trapper",
    "Witch",
    "Woodcutter",
]
job_type = [civilized_job, underworld_job, wilderness_job]
divine_domains = [
    animals,
    elements,
    "Balance",
    "Betrayal",
    "Chance",
    "Chaos",
    "Conquest",
    "Cycles",
    "Death",
    "Destiny",
    "Dreams",
    "Gateways",
    "Judgement",
    "Love",
    "Memory",
    "Monsters",
    "Moon",
    "Motherhood",
    "Oaths",
    "Order",
    "Plague",
    "Purification",
    "Reason",
    "Schemes The Sea",
    "Secrets",
    "Storms",
    "Summer",
    "Sun",
    "The Forge",
    "The Wild",
    "Time",
    "Underworld",
    "Wealth",
    "Winter",
]
mission_targets = [
    "VIP-NPC",
    "Building/Monument",
    "Local Business",
    "Government Office",
    "Underworld 'Office'"
]
missions = [
    "Apprehend",
    "Assassinate",
    "Blackmail",
    "Burgle",
    "Chart",
    "Convince",
    "Deface",
    "Defraud",
    "Deliver",
    "Destroy",
    "Discredit",
    "Escort",
    "Exfiltrate",
    "Extort",
    "Follow",
    "Frame",
    "Impersonate",
    "Impress",
    "Infiltrate",
    "Interrogate",
    "Investigate",
    "Kidnap",
    "Locate",
    "Plant",
    "Protect",
    "Raid",
    "Replace",
    "Retrieve",
    "Rob",
    "Ruin",
    "Sabotage",
    "Smuggle",
    "Surveil",
    "Take over",
    "Terrorize",
    "Threaten",
]
book_sub = [
    "Alchemy",
    "Art",
    "Astrology",
    "Blackmail",
    "Charts & maps",
    "Conspiracies",
    "Cookbook",
    "Criminals",
    "Divination",
    "Etiquette",
    "Fashion",
    "Genealogy",
    "History",
    "Journal",
    "Language",
    "Laws",
    "Letters",
    "Lost empires",
    "Lost places",
    "love poems",
    "Monsters",
    "Mythology",
    "Odd customs",
    "Oratory",
    "Propaganda",
    "Prophecies",
    "Siege-craft",
    "Songs",
    "State secrets",
    "Sword fighting",
    "Theology",
    "Treasures",
    "War chronicle",
    "Witch-hunting"
]
omens = [
    "All Iron rusts",
    "Animals Die",
    ("Animals mutate: ", mutations),
    "Birds attack",
    "City Appears",
    "Deadly fog",
    "Dream plague",
    "Endless night",
    "Endless rain",
    "Endless storm",
    "Endless twilight",
    "Endless winter",
    "Fae return",
    "Forest appears",
    "Forgetfulness",
    "Graves open",
    "Lamentations",
    "Maggots",
    ("Mass insanity: ", insanities),
    ("Mass mutation: ", mutations),
    "Mass slumber",
    "Meteor strike",
    "Mirrors speak",
    "No Stars",
    "Outsider enters",
    "People shrink",
    "People vanish",
    "Plants wither",
    "Portal opens",
    "Rifts open",
    "Shadows speak",
    "Space distorts",
    "Stones speak",
    "Total silence",
    "Tower appears",
    "Water to blood"
]
after_party = [
    "Absurd boasts",
    "Adopted a child",
    "Awarded medal",
    "Bought the inn",
    "Cursed",
    "Duel scheduled",
    "Elected to office",
    "Given a quest",
    "Got married",
    "In a coffin",
    "In Love",
    "In the stocks",
    "Inconvenient pet",
    "Insulted a noble",
    ("Insulted faction :", factions),
    "Joined a cult",
    "Letter of thanks",
    "Lost",
    "Lost at gambling",
    "Lost reputation",
    "New identity",
    "New tattoo",
    "Poisoned",
    "Recruited",
    "Robbed",
    "Sick",
    "Signed contract",
    "Someone died",
    "Spilled secrets",
    "Started a cult",
    "Swindled",
    "Thrown in jail",
    "Wrong clothes"
]
treasure_traits = [
    "Altered",
    "Ancient",
    "Blessed",
    "Bulky",
    "Compact",
    "Consumable",
    "Cultural value",
    "Cursed",
    "Damaged",
    "Disguised",
    "Draws enemies",
    effects,
    elements,
    "Embellished",
    "Encoded",
    "Exotic",
    "Extra-planar",
    "Famous",
    "Forbidden",
    "Fragile",
    "Heavy",
    "Immovable",
    "Impracticable",
    "Indestructible",
    "Intelligent",
    "Masterwork",
    "Military value",
    "Owned",
    "Partial",
    "Political value",
    "Religious value",
    "Repaired",
    "Royal",
    "Toxic",
    "Vile"
]
ordinary_materials = [
    "wood",
    "stone",
    "animal bone",
    "clay",
    "leather",
    "cloth",
    "paper",
    "brass",
    "bronze",
    "copper",
    "iron",
    "metal",
    "tin",
    "steel",
]
materials = [
    valuable_materials,
    ordinary_materials
]
potions = [
    animal_form,
    insanities,
    mutations,
    mob_ability,
    mob_feat,
    mob_trait,
    "Body swap",
    "Camouflage",
    "Control animals",
    ("Control ", elements),
    (elements, " form"),
    (elements, " skin"),
    (lootType, " form"),
    ("Spell :", magic_formula),
    "Cure affliction",
    "Detect evil",
    "Detect gold",
    "Detect hidden",
    "Direction sense",
    "Extra arm",
    "Flight",
    "Ghost-speech",
    "Heat vision",
    "Invulnerable",
    "Magic immunity",
    "Mirror-image",
    "Night vision",
    "Restore health",
    "Speed",
    "Stretchy",
    "Super-jump",
    "Super-strength",
    "Telekinesis",
    "Tongues",
    "Water-breathing",
    "Water-walking",
]
edible_plants = [
    "Acorns",
    "Apples",
    "Asparagus",
    "Blackberries",
    "Blueberries",
    "Carrots",
    "Cattail",
    "Cherries",
    "Chickweed",
    "Chicory",
    "Clover",
    "Dandelion",
    "Dead-nettle",
    "Elderberries",
    "Fireweed",
    "Gooseberries",
    "Hazelnuts",
    "Henbit",
    "Hickory nuts",
    "Honeysuckle",
    "Leeks",
    "Milk thistle",
    "Mint",
    "Mushrooms",
    "Mustard",
    "Onion",
    "Pecans",
    "Persimmons",
    "Raspberries",
    "Strawberries",
    "Walnuts",
    "Watercress",
    "Wild garlic",
    "Wild grapes",
    "Wood sorrel",
]
poisonous_plants = [
    "Angel’s Trumpet",
    "Baneberry",
    "Belladona",
    "Black Truffle",
    "Bleeding Heart",
    "Celandine",
    "Cocklebur",
    "Columbine",
    "Crowncup",
    "Death Cap",
    "Dumbcane",
    "Foxglove",
    "Hemlock",
    "Hogweed",
    "Holly",
    "Horse Chestnut",
    "Hyacinth",
    "Ivy",
    "Jessamine",
    "Kudu",
    "Larkspur",
    "Mandrake",
    "Mangrove",
    "Mistletoe",
    "Moonflower",
    "Nightshade",
    "Oleander",
    "Ragwort",
    "Reindeer Lichen",
    "Snakeweed",
    "Spindle",
    "Stinkhorn",
    "Waxcap",
    "Wine-Cap",
    "Wolfsbane",
    "Wormwood",
]
magic_ingredients = [
    animals,
    edible_plants,
    poisonous_plants,
    mob_feat,
    potions,
    phy_ele,
    valuable_materials,
    ("Book Page: ", book_sub),
    "Ancient liquor",
    "Blind eye",
    "Boiled cat",
    "Bottled fog",
    "Coffin nail",
    "Corpse’s hair",
    "Crossroad dust",
    "Cultist entrails",
    "Exotic spice",
    "Killer’s hand",
    "King’s tooth",
    "Last breath",
    "Liar’s tongue",
    "Lightning bolt",
    "Lodestone",
    "Monk’s vow",
    "Newborn’s cry",
    "Oil portrait",
    "Pyre ember",
    "Queen bee",
    "Queen’s blood",
    "Ship’s barnacle",
    "Star-metal",
    "Thief's finger",
    "Tomb Flower",
    "Wedding ring",
    "Widow’s tears",
    "Wizard skull",
]
up_class_build = [
    "Academy",
    "Alchemist",
    "Archive",
    "Art dealer",
    "Barber",
    "Bookbinder",
    "Bookseller",
    "Castle",
    "Clockmaker",
    "Clothier",
    "Courthouse",
    "Furrier",
    "Gallery",
    "Garden",
    "Haberdashery",
    "Jeweler",
    "Law office",
    "Locksmith",
    "Lounge",
    "Manor",
    "Museum",
    "Observatory",
    "Opera house",
    "Park",
    "Physician",
    "Printer",
    "Public baths",
    "Restaurant",
    "Salon",
    "Stables",
    "Taxidermist",
    "Temple",
    "Tobacconist",
    "Town house",
    "Winery",
    "Zoo",
]
low_class_build = [
    "Apothecary",
    "Asylum",
    "Baker",
    "Brewery",
    "Butcher",
    "Candlemaker",
    "Catacombs",
    "Cheese-maker",
    "Criminal den",
    "Curiosity shop",
    "Dock",
    "Fighting pit",
    "Forge",
    "Fortuneteller",
    "Gambling hall",
    "Leather-works",
    "Marketplace",
    "Mason",
    "Mill",
    "Moneylender",
    "Orphanage",
    "Outfitter",
    "Prison",
    "Sewers",
    "Shipyards",
    "Shrine",
    "Stockyard",
    "Stone-carver",
    "Tattooist",
    "Tavern",
    "Theater",
    "Veterinarian",
    "Warehouse",
    "Watchtower",
    "Weaver",
    "Workshop",
]
build_rooms = [
    "Arboretum",
    "Atrium",
    "Attic",
    "Aviary",
    "Ballroom",
    "Baths",
    "Bed chamber",
    "Cabinet",
    "Chapel",
    "Cloakroom",
    "Dining room",
    "Dressing room",
    "Garden",
    "Garret",
    "Greenhouse",
    "Junk room",
    "Kitchen",
    "Larder",
    "Library",
    "Map room",
    "Menagerie",
    "Mews",
    "Nursery",
    "Pantry",
    "Parlor",
    "Privy",
    "Root cellar",
    "Saucery",
    "Scullery",
    "Smoking room",
    "Spicery",
    "Still room",
    "Study",
    "Trophy room",
    "Wardrobe",
]
city_acts = [
    "Abduct",
    "Beg",
    "Brawl",
    "Burgle",
    "Celebrate",
    "Chase",
    "Construct",
    "Cook",
    "Dance",
    "Duel",
    "Execute",
    "Extinguish",
    "Extort",
    "Follow",
    "Gamble",
    "Haul",
    "Interrogate",
    "Marry",
    "Mourn",
    "Party",
    "Patrol",
    "Perform",
    "Play",
    "Preach",
    "Process",
    "Proclaim",
    "Protest",
    "Release",
    "Repair",
    "Riot",
    "Rob",
    "Search",
    "Sell",
    missions,
]
city_events = [
    "Assassination",
    "Carnival",
    "Conscription",
    "Coronation",
    "Coup",
    "Cult activity",
    "Curfew",
    "Discovery",
    "Earthquake",
    "Fashion trend",
    "Fire",
    "Flood",
    "Heavy fog",
    "Heavy taxes",
    "Holy day",
    "Hysteria",
    "Inquisition",
    "Insurrection",
    "Invasion",
    "Jailbreak",
    "Mass eviction",
    "Mass pardon",
    "Negotiations",
    "Plague",
    "Proclamation",
    "Prohibition",
    "Public games",
    "Refugees",
    "Rioting",
    "Roundup",
    "Scandal",
    "Serial killer",
    "Shortage",
    "Tournament",
    "Trial",
    (factions, " War"),
]
district_themes = [
    "Catacombs",
    "Construction",
    "Crafts",
    "Criminality",
    "Culture",
    "Dining",
    "Education",
    "Entertainment",
    "Finance",
    "Foreigners",
    "Ghettoes",
    "Government",
    "Graveyards",
    "Green space",
    "Industrialization",
    "Judgement",
    "Livestock",
    "Marketplace",
    "Memorials",
    "Military",
    "Opulence",
    "Pollution",
    "Poverty",
    "Punishment",
    "Religion Vices",
    "Science",
    "Trade",
    "Trash",
    "Wizardry",
    "Wonders",
    civilized_job,
    low_class_build,
    up_class_build,
    underworld_job,
    wilderness_job,
]
city_themes = [
    "Aristocracy",
    "Art",
    "Bureaucracy",
    "Castes",
    "Catacombs",
    "Crime families",
    "Cruelty",
    "Festivals",
    "Feuds",
    "Intrigue",
    "Martial law",
    "Meritocracy",
    "Opulence",
    "Pilgrimages",
    "Piracy",
    "Plutocracy",
    "Poverty",
    "Rituals",
    "Slavery",
    "Spices",
    "Theocracy",
    "Thievery",
    "Trade",
    "Tyranny",
    "Wizardry",
    "Xenophobia",
    animals,
    city_acts,
    city_events,
    factions,
    divine_domains,
    job_type,
    phy_ele,
    up_class_build,
    low_class_build,
    district_themes,
]
faction_traits = [
    "Bankrupt",
    "Bureaucratic",
    "Charitable",
    "Confused",
    "Connected",
    "Corrupt",
    "Decadent",
    "Decaying",
    "Delusional",
    "Divided",
    "Dwindling",
    "Efficient",
    "Esoteric",
    "Expanding",
    "Hunted",
    "Incompetent",
    "Incorruptible",
    "Insane",
    "Insular",
    "Manipulative",
    "Martial",
    "Pious",
    "Popular",
    "Righteous",
    "Ruthless",
    "Secret",
    "Subversive",
    "Suppressed",
    "Threatened",
    "Thriving",
    "Unpopular",
    "Up-and-coming",
    "Wealthy",
    "Well-prepared",
    "Xenophobic",
    personality,
]
faction_goals = [
    "Advise leader",
    "Avoid detection",
    "Awaken being",
    "Collect artifacts",
    "Construct base",
    "Control politics",
    "Create artifact",
    "Defeat leader",
    "Defend borders",
    "Destroy artifacts",
    "Destroy being",
    "Destroy villain",
    "Enforce law",
    "Enrich members",
    "Entertain",
    "Exchange goods",
    "Hear rumors",
    "Indulge tastes",
    "Map the wild",
    "Overthrow order",
    "Preserve lineage",
    "Preserve lore",
    "Produce Goods",
    "Promote arts",
    "Promote Craft",
    "Purge traitors",
    "Sell services",
    "Share knowledge",
    "Spread beliefs",
    "Summon evil",
    "Survive",
    "Transport goods",
    ("Create ", animals),
    ("Control ", factions),
    ("Defeat ", factions),
    ("Infiltrate ", factions),
]
wild_hazards = [
    "Avalanche",
    "Blizzard",
    "Brushfire",
    "Cloudburst",
    "Cyclone",
    "Dense fog",
    "Downpour",
    "Drizzle",
    "Dust storm",
    "Earthquake",
    "Eruption",
    "Flooding",
    "Forest fire",
    "Hail",
    "Heat wave",
    "Hurricane",
    "Ice storm",
    "Light mist",
    "Locust swarm",
    "Magma flow",
    "Meteor strike",
    "Monsoon",
    "Mudflow",
    "Mudslide",
    "Predator",
    "Quicksand",
    "Rain of frogs",
    "Rock slide",
    "Sandstorm",
    "Sleet",
    "Snow",
    "Stampede",
    "Thunderstorm",
    "Tsunami",
    "Whirlpool",
    "Windstorm",
]
inn_adj = [
    "Bellowing",
    "Blazing",
    "Bleak",
    "Blessed",
    "Bloody",
    "Copper",
    "Crimson",
    "Cunning",
    "Dancing",
    "Dead",
    "Drunken",
    "Flying",
    "Ghastly",
    "Golden",
    "Helpful",
    "Hideous",
    "Howling",
    "Hungry",
    "Moldy",
    "Muttering",
    "Nimble",
    "Oozing",
    "Petrified",
    "Prancing",
    "Romantic",
    "Salty",
    "Shivering",
    "Shrieking",
    "Silver",
    "Singing",
    "Smoking",
    "Thirsty",
    "Tipsy",
    "Wanton",
    "Whistling",
    "Wicked",
]
wild_regions = [
    "Ashy",
    "Badlands",
    "Bay",
    "Beach",
    "Delta",
    "Desert",
    "Dry lands",
    "Dune sea",
    "Dust bowl",
    "Fjords",
    "Flood lands",
    "Foothills",
    "Forest",
    "Glaciers",
    "Heath",
    "Highlands",
    "Hills",
    "Ice fields",
    "Jungle",
    "Lowlands",
    "Mesas",
    "Moor",
    "Mountains",
    "Petrified forest",
    "Plains",
    "Rain-forest",
    "River lands",
    "Salt Pan",
    "Savanna",
    "Steppe",
    "Taiga",
    "Thickets",
    "Tundra",
    "Volcanic plain",
    "Wetlands",
    "Woodlands",
]
wild_landmarks = [
    "Bog",
    "Boulder field",
    "Butte",
    "Cave",
    "Cliff",
    "Crag",
    "Crater",
    "Creek",
    "Crossing",
    "Ditch",
    "Field",
    "Forest",
    "Grove",
    "Hill",
    "Hollow",
    "Hot springs",
    "Lair",
    "Lake",
    "Lake-bed",
    "Marsh",
    "Mesa",
    "Moor",
    "Pass",
    "Pit",
    "Pond",
    "Rapids",
    "Ravine",
    "Ridge",
    "Rise",
    "River",
    "Rock-slide",
    "Spring",
    "Swamp",
    "Thickets",
    "Valley",
    "Waterfall",
]
wild_structures = [
    "Altar",
    "Aqueduct",
    "Bandit’s camp",
    "Battlefield",
    "Bonfire",
    "Bridge",
    "Cairn",
    "Crossroads",
    "Crypt",
    "Dam",
    "Dungeon",
    "Farm",
    "Ford",
    "Fortress",
    "Gallows",
    "Graveyard",
    "Hedge",
    "Hunter’s camp",
    "Inn",
    "Lumber camp",
    "Mine",
    "Monastery",
    "Monument",
    "Orchard",
    "Outpost",
    "Pasture",
    "Ruin",
    "Seclusion",
    "Shack",
    "Shrine",
    "Standing stone",
    "Temple",
    "Village",
    "Wall",
    "Watchtower",
    "Way-stone",
]
inn_nouns = [
    "Axe",
    "Barrel",
    "Bear",
    "Bell",
    "Boot",
    "Bowl",
    "Bucket",
    "Candle",
    "Cock",
    "Cow",
    "Dragon",
    "Egg",
    "Elephant",
    "Flea",
    "Fork",
    "Giant",
    "Griffin",
    "Hart",
    "Hog",
    "Hound",
    "Lamb",
    "Lion",
    "Mackerel",
    "Maid",
    "Monk",
    "Moon",
    "Pipe",
    "Prince",
    "Rat",
    "Skull",
    "Spoon",
    "Star",
    "Swan",
    "Sword",
    "Whale",
    "Wife",
]
wild_acts = [
    "Ambush",
    "Argue",
    "Birth",
    "Build",
    "Bury",
    "Capture",
    "Convene",
    "Demolish",
    "Die",
    "Duel",
    "Eat",
    "Excavate",
    "Feast",
    "Felling",
    "Fish",
    "Flee",
    "Forage",
    "Hunt",
    "March",
    "Raid",
    "Rescue",
    "Rest",
    "Sacrifice",
    "Scout",
    "Sing",
    "Skin",
    "Skirmish",
    "Slay",
    "Sleep",
    "Swim",
    "Track",
    "Trap",
    "Wander",
    "Worship",
    city_acts,
]
inn_quirks = [
    "100 years in past",
    "Always night",
    "Animal fights",
    "Bard duels",
    "Bigger inside",
    "Black market",
    "Brand new",
    "Cannibals",
    "Constant party",
    "Dancing contest",
    "Dead drop",
    "Expensive",
    "Famous chef",
    "Fey patrons",
    "Fight club",
    "Five floors",
    "Ghost staff",
    "Haunted",
    "Hideout",
    "Magic sword",
    "Magically moves",
    "Mercenaries for hire",
    "Preaching",
    "Secure storage",
    "Staff are kids",
    "Talking painting",
    "Underground",
    "VIP lounge",
    "Voice in well",
    "Women only",
    city_acts,
    (factions, " hangout"),
    faction_traits,
    (job_type, " hangout"),
    ("Inn/", up_class_build + low_class_build),
]
dun_enter = [
    "All libraries",
    "Beaver dam",
    "Behind waterfall",
    "Chalk rectangle",
    "Chest bottom",
    "Chimney",
    "Cupboard",
    "Dolmen shadow",
    "Down a well",
    "Fiery pit",
    "Fog road",
    "Forest spring",
    "Giant book",
    "Gypsy wagon",
    "Hollow tree",
    "Huge keyhole",
    "Iron maiden",
    "Living tattoo",
    "Magic painting",
    "Man-shape hole",
    "Maze potion",
    "Mirror",
    "Monster mouth",
    "Monster wound",
    "Narrow alley ",
    "Rain door",
    "Sewer grate",
    "Sudden rift",
    "Tidal cave",
    "Tower top",
    "Tree roots",
    "Under the bed",
    "Unfolded map",
    "Up a tree",
    "Whirlpool",
    "Wine barrel",
]
dun_rooms = [
    "Armory",
    "Banquet hall",
    "Barracks",
    "Catacombs",
    "Cavern",
    "Chasm",
    "Courtyard",
    "Crypt",
    "Dormitory Kennel ",
    "Fighting pit",
    "Forge",
    "Fountain",
    "Gate house",
    "Guard room",
    "Laboratory",
    "Mess hall",
    "Mine shaft",
    "Museum ",
    "Oubliette",
    "Pool",
    "Prison",
    "Record-room",
    "Shrine",
    "Slaughterhouse",
    "Stables",
    "Storeroom",
    "Throne-room",
    "Torture room",
    "Treasury",
    "Vault",
    "Well",
    "Workshop ",
    build_rooms,
    up_class_build,
    low_class_build,
]
dun_forms = [
    "Arena",
    "Asylum",
    "Aviary",
    "Bank",
    "Baths",
    "Body ",
    "Casino",
    "Catacombs",
    "Cave",
    "Court",
    "Forge",
    "Garden",
    "Hideout",
    "Hotel",
    "Laboratory",
    "Library",
    "Market",
    "Mine",
    "Monastery",
    "Museum",
    "Nursery",
    "Orphanage",
    "Palace",
    "Prison",
    "Sewer",
    "Ship",
    "Slave pit",
    "Temple",
    "Theater",
    "University",
    "Vault",
    "Zoo",
    build_rooms,
    dun_rooms,
    up_class_build,
    low_class_build
]
dun_layout = [
    "Ant colony",
    "Central hub",
    "Claustrophobic",
    "Crisscrossing",
    "Curved",
    "Disorienting",
    "Galleria",
    "Geometric",
    "Gonzo",
    "Haphazard",
    "Highly regular",
    "Honeycomb",
    "Intertwined",
    "Isolated wings",
    "Layered",
    "Linear",
    "Loops",
    "Many corridors",
    "Mazes",
    "Mix of layouts",
    "Multiple hubs",
    "No corridors",
    "Open plan",
    "Open voids",
    "Organic",
    "Oversized",
    "Recursive",
    "Repetitive",
    "Sprawling",
    "Suspended",
    "Symbol shape",
    "Tall and narrow",
    "Themed zones",
    "Vertical",
    "Winding",
    "Ziggurat",
]
dun_ruins = [
    "Arcane disaster",
    "Army invasion",
    "Cannibalism",
    "Civil war",
    "Collapse",
    "Crystal growth",
    "Curse",
    "Degeneration",
    "Earthquake",
    "Eruption",
    "Evil unearthed",
    "Experiments",
    "Explosion ",
    "Famine",
    "Fire",
    "Flooding ",
    "Fungus",
    "Haunting",
    "Ice",
    "Lava flow",
    "Magical sleep",
    "Melted",
    "Monster attack",
    "Outsider attack",
    "Overgrowth Revolt",
    "Petrification",
    "Plague",
    "Planar overlay",
    "Poison gas",
    "Resources gone",
    "Risen dead",
    "Too many traps",
    "War",
    mutations,
    insanities
]
dun_hazards = [
    "Acid drip",
    "Bloodsuckers",
    "Cave-in",
    "Choking dust",
    "Crude oil",
    "Crystal shards",
    "Deafening noise",
    "Dense fog",
    "Ensnaring vines",
    "Fallen floor",
    "Flooding",
    "Freezing",
    "Geysers",
    "Magma",
    "Magnetic field",
    "Mud flow",
    "Narrow ledge",
    "Narrow passage",
    "Poison goo",
    "Poison plants",
    "Precipice",
    "Quicksand",
    "Radiation",
    "Rock-slide",
    "Rotten ceiling",
    "Rotten floor",
    "Sinkhole",
    "Slippery slope",
    "Spider webs",
    "Spores",
    "Steam vents",
    "Strong winds",
    "Tar pit",
    "Tight passage",
    "Toppling object",
    "Toxic fumes",
]
dun_rewards = [
    "Ancient lore",
    "Animal ally",
    "Army",
    "Blessing",
    "Blueprints",
    "Cultural artifact",
    "Enemy weakness",
    "Faction ally",
    "Forewarning",
    "Guide",
    "Holy relic",
    "Influential ally",
    "Instructions",
    "Jewels",
    "Key",
    "Lost formula",
    "Machine",
    "Magical ally",
    "Map",
    "Marital ally",
    "Masterpiece",
    "Oracle",
    "Piles of loot",
    "Planar portal",
    "Prophecy",
    "Renown",
    "Spell",
    "Transformation",
    "Transport",
    "Uncovered plot",
    "Vision",
    "Weapon",
    ("Magic ", lootType),
    lootType,
    (animals, " ally"),
    valuable_materials,
]
dun_acts = [
    "Besiege",
    "Capture",
    "Collect",
    "Construct",
    "Control",
    "Deliver",
    "Demolish",
    "Escape",
    "Feed",
    "Fortify",
    "Guard",
    "Hide",
    "Hunt",
    "Loot",
    "Map",
    "Mine",
    "Negotiate",
    "Patrol",
    "Perform ritual",
    "Purge",
    "Question",
    "Raid",
    "Repair",
    "Rescue",
    "Research",
    "Revive",
    "Riddle",
    "Scavenge",
    "Seize",
    "Tunnel",
    "Unearth",
    "Vandalize",
    "Worship",
    city_acts,
    wild_acts,
    mob_tactics,
]
dun_room_details = [
    "Bas-relief",
    "Blood trail",
    "Bones",
    "Chains",
    "Chalk marks",
    "Claw marks",
    "Corpses",
    "Cracked beams",
    "Crumbling walls",
    "Decaying food",
    "Decaying nest",
    "Dripping water",
    "Fading murals",
    "Faint breeze",
    "Faint footsteps",
    "Fallen pillars",
    "Fungus",
    "Furniture",
    "Graffiti",
    "Mosaics",
    "Recent repairs",
    "Rotting books",
    "Rubble",
    "Shed skin",
    "Slime trails",
    "Smoke stains",
    "Spider webs",
    "Stalactites",
    "Stench",
    "Thick dust",
    "Torn clothes",
    "Tree roots",
    "Unusual smell",
    "Vibrations",
    "Vines",
    "Whispers",
]
dun_tricks = [
    "Absorption",
    "Activation",
    "Animation",
    "Blessings",
    "Communication Duplication",
    "Confusion",
    "Consumption",
    "Creation",
    "Curses",
    "Deception",
    "Exchange",
    "Imprisonment",
    "Instructions",
    "Interrogation",
    "Mind-control",
    "Mood-alteration Release",
    "Nullification",
    "Plane-shift",
    "Protection",
    "Rejuvenation",
    "Reversal",
    "Rotation",
    "Scrying",
    "Size-alteration",
    "Summoning",
    "Theft",
    "Time-alteration",
    "Transformation",
    "Transmutation",
    "Transportation",
    "Wonder",
    eth_efc,
    phy_efc,
    missions
]
trap_effects = [
    "Acid pool",
    "Adhesive",
    "Alarm",
    "Armor melts",
    "Bear trap",
    "Blinding spray",
    "Blunt pendulum",
    "Boiling tar",
    "Collapsing floor",
    "Crocodile pit",
    "Crushing walls",
    "Deep pit",
    "Falling cage",
    "Falling ceiling",
    "Fills with sand",
    "Flooding",
    "Giant magnet",
    "Hard vacuum",
    "Lava flow",
    "Lightning",
    "Living statues",
    "Missile fire",
    "Net trap",
    "Pendulum blade",
    "Poison gas",
    "Poison needle",
    "Quicksand",
    "Rage gas",
    "Rolling boulder",
    "Room freezes",
    "Room on fire",
    "Sleeping gas",
    "Spiked pit",
    "Tombs open",
    "Wall spikes",
    (animals, " freed"),
]
trap_triggers = [
    "Blow",
    "Break",
    "Burn",
    "Choice",
    "Countdown",
    "Darkness",
    "Drain",
    "Eat",
    "Insert",
    "Kill",
    "Knock",
    "Light",
    "Magic",
    "Melody",
    "Noise",
    "Open",
    "Phrase",
    "Pour",
    "Press",
    "Proximity",
    "Pull",
    "Read",
    "Reflect",
    "Release",
    "Remove",
    "Retrieve",
    "Rudeness",
    "Shut",
    "Sit",
    "Sleep",
    "Slide",
    "Touch",
    "Turn",
    "Unbalance",
    "Unearth",
    "Write",
]
tactical_street = [
    "Arcade",
    "Awnings",
    "Balconies",
    "Barricades",
    "Bridge",
    "Canal",
    "Carriages",
    "Catwalks",
    "Climbable walls",
    "Clotheslines",
    "Crowd",
    "Dead end",
    "Dense fog",
    "Downpour",
    "Flooding",
    "Food stalls",
    "Fountain",
    "Gates",
    "Ladders",
    "Livestock",
    "Muddy",
    "Overgrown",
    "Roof access",
    "Roof gardens",
    "Sewer access",
    "Sinkhole",
    "Slick",
    "Steep roofs",
    "Steep streets",
    "Steps",
    "Torn up street",
    "Vermin swarms",
    "Well",
    city_acts,
    dun_acts,
    wild_acts,
]
tactical_building = [
    "Balconies",
    "Basement access",
    "Brightly lit",
    "Broken furniture",
    "Broken glass",
    "Cabinets",
    "Carpeted floors",
    "Chandeliers",
    "Crawlspaces",
    "Drain pipes",
    "Dumbwaiters",
    "Echoing marble",
    "Hanging chains",
    "Huge fireplace",
    "Narrow ledges",
    "Open windows",
    "Ornate weapons",
    "Overgrown",
    "Patrols",
    "Piles of trash",
    "Pillars",
    "Rotting ceiling",
    "Rotting floors",
    "Rotting walls",
    "Screens",
    "Servant passages",
    "Sewer access",
    "Shadowy alcoves",
    "Skylights",
    "Spy-holes",
    "Staircases",
    "Tall bookshelves",
    "Unlit",
    "Watchdogs",
    "Window drapes",
    (animals, " nest"),
    city_acts,
    dun_acts,
]
wild_region_traits = [
    "Ashen",
    "Blasted",
    "Blighted",
    "Broken",
    "Consuming",
    "Corrupted",
    "Creeping",
    "Desolate",
    "Eternal",
    "Forsaken",
    "Frozen",
    "Haunted",
    "Howling",
    "Jagged",
    "Lonely",
    "Misty",
    "Perilous",
    "Petrified",
    "Phantasmal",
    "Ravenous",
    "Savage",
    "Shadowy",
    "Shifting",
    "Shivering",
    "Sinister",
    "Sinking",
    "Smoldering",
    "Sweltering",
    "Thorny",
    "Thundering",
    "Torrential",
    "Trait",
    "Wandering",
    "Withered",
    eth_efc,
    phy_efc,
    dun_tricks,
]
wild_discoveries = [
    "Blood stains",
    "Bones",
    "Broken weapons",
    "Burrow",
    "Cut ropes",
    "Dead animal",
    "Food scraps",
    "Grave marker",
    "Human corpse",
    "Magical effect",
    "Map",
    "Message",
    "Migration",
    "Nest",
    "Portal",
    "Resources",
    "Rift",
    "Strange plant",
    "Supplies",
    "Torn flag",
    "Tracks",
    "Trap",
    "Treasure cache",
    "Wizard fight",
    city_acts,
    civilized_job,
    lootType,
    ("Lost ", job_type),
    ("Stunned ", job_type),
    mutations,
    underworld_job,
    wilderness_job,
    wild_landmarks,
    wild_structures,
    wild_acts,
    dun_acts,
]
name_male_big = name_male_short + name_male_mr + name_male_apriori
name_male_full = name_male_big + name_male_gothic + name_male_old
name_female_big = name_female_short + name_female_mr + name_female_apriori
name_female_full = name_female_big + name_female_gothic + name_female_old
name_big = name_male_big + name_female_big
name_full = name_male_full + name_female_full
surname_all = surname_other + surname_lower_mr + surname_upper_mr

city_acts.append(dun_acts)
city_acts.append(wild_acts)
wild_acts.append(dun_acts)
inn_quirks.append(dun_forms)

mr_pages = [
    ("PC", ["character_items", "appear", "phys", "character_background", "clothing", "personality", "mannerism"]),
    ("Magic", ["phy_efc", "phy_ele", "phy_form", "eth_efc", "eth_ele", "eth_form", "mutations", "insanities", "omens"]),
    ("Monster",
        [
            "arial",
            "land",
            "sea",
            "mob_feat",
            "mob_trait",
            "mob_ability",
            "mob_tactics",
            "mob_person",
            "mob_weak"
            ]),
    ("Character",
        [
            "after_party",
            "appear",
            "asset",
            "civilized_job",
            "clothing",
            "divine_domains",
            "hobbies",
            "liability",
            "life_goal",
            "mannerism",
            "methods",
            "misfortune",
            "missions",
            "name_female_mr",
            "name_male_mr",
            "personality",
            "phys",
            "relationships",
            "reputation",
            "secret",
            "surname_lower_mr",
            "surname_upper_mr",
            "underworld_job",
            "wilderness_job",
        ]),
    ("Treasure & Equipment",
        [
            "book_sub",
            "magic_ingredients",
            "misc_items",
            "potions",
            "tool_items",
            "treasure_items",
            "treasure_traits",
            "valuable_materials",
            "weapon_items",
            "worn_items",
        ]),
    ("The City",
        [
            "city_themes",
            "city_events",
            "district_themes",
            "up_class_build",
            "low_class_build",
            "city_acts",
            "build_rooms",
            "tactical_street",
            "tactical_building",
            "factions",
            "faction_traits",
            "faction_goals"
        ]),
    ("The Wild",
        [
            "wild_regions",
            "wild_landmarks",
            "wild_structures",
            "wild_region_traits",
            "wild_discoveries",
            "wild_acts",
            "wild_hazards",
            "edible_plants",
            "poisonous_plants",
            "inn_adj",
            "inn_nouns",
            "inn_quirks",
        ]),
    ("The Maze",
        [
            "dun_enter",
            "dun_forms",
            "dun_layout",
            "dun_ruins",
            "dun_acts",
            "dun_rooms",
            "dun_room_details",
            "dun_tricks",
            "dun_hazards",
            "dun_rewards",
            "trap_effects",
            "trap_triggers",
        ]),
]
